### ISSUE TITLE
About feedback from mapping

### ISSUE THREAD

**Issue by canyou2014** [rpng/R-VIO#10]
I have read this paper https://arxiv.org/abs/1903.08636,  it is about feedback map point to MSCKF by Schmidt-EKF. If I wan to realize Schmidt-EKF on  R-VIO，How should I propagate the covariance matrix  PAS?

**Comment by goldbattle** [comment]
Thanks for being interested in both of those projects.
You can propagate the P_as using equation (7) in that [paper](https://arxiv.org/pdf/1903.08636.pdf):
![image](https://user-images.githubusercontent.com/2222562/62047347-3f073500-b1d8-11e9-967d-b432d9fc4ef6.png)

An important note is that the schmidt states do not evolve with time as they are represented in the global frame of reference. If you represent your SLAM features in the robot centric frame then you lose the computational advantage as you need to perform the "composition" to warp the features after each update. You should look more carefully into this part.

**Comment by huaizheng** [comment]
Hi @canyou2014, for such extended problem I recommend you to directly email either me or @goldbattle for discussion, which I think it is better than opening an issue. Thank you.
