### ISSUE TITLE
Does Gaussian thresholding and Box blurring help?

### ISSUE THREAD

**Issue by JiatianWu** [rpng/R-VIO#11]
I noticed that you mentioned using Guassian thresholding and box blurring on image before doing the KLT track, but I did not find implementation in your code. I wonder that do these two tricks help with image blur/dark/ varying light problems?

**Comment by huaizheng** [comment]
To present a complete VIO system, in the current front end I adopt standard histogram equalization to preprocess the image, which is commonly used to deal with the illumination change. Also, in my paper I instead used the above combination to process the image and help the visual tracking. As I have modularized the R-VIO codebase, you could try different front end with our proposed back end (robocentric estimator) to see whether it improves the performance.
