### ISSUE TITLE
Planar moves demonstration

### ISSUE THREAD

**Issue by K0stIa** [rpng/R-VIO#12]
In the paper, you state that r-vio works fine in case of planar movements. This is very cool If it really works with no wheel odometry! 
Could you provide a dataset where r-vio works fine in case of planar movements? I missed these experiments in the paper. :(

I tried my own dataset, though I am failing, possibly due to bad thresholds.

**Comment by huaizheng** [comment]
@K0stIa, thanks for testing our code. R-VIO is designed to estimate 6-DOF pose of the sensing platform, so definitely it can be used to replace the wheel odometry for 2D navigation. Also, this has already been validated by the Monte-Carlo simulation, handheld and urban driving tests that we show in the papers. Recently I have updated the codebase including the initialization part, please feel free to test again on your own sensing platform.
