### ISSUE TITLE
Camera-IMU temporal extrinsic not being set in code

### ISSUE THREAD

**Issue by jeffcyu** [rpng/R-VIO#14]
Hi Zheng Huai and co,

I am still working through the setup I described in [https://github.com/rpng/R-VIO/issues/13](url), but while I was working on it I noticed that changes I made to Camera.nTimeOffset parameter in the yaml would not be loaded into the code (ie. mnCamTimeOffset = 0.0 always). Looking a little further there seems to be a bit of a typo:

In line 65 of rvio_euroc.yaml:
`Camera:nTimeOffset: 0`
And in line 71 of System.cc:
`mnCamTimeOffset = fsSettings["Camera.nTimeOffset"];`

Note the (:) vs the (.). I changed the colon to a period and the parameter now loads.

Best,
~Jeff

**Comment by huaizheng** [comment]
Thanks.
