### ISSUE TITLE
parameter configuration of the urban driving dataset

### ISSUE THREAD

**Issue by zbqq** [rpng/R-VIO#16]
Could you share the parameter configuration of the urban driving dataset?

**Comment by huaizheng** [comment]
@zbqq all the config files have the same format, and the difference is the values of sensor parameters for IMU and camera, e.g., noise, intrinsic, and extrinsic parameters, which I marked as "fixed". And the values of the other parameters can be set based on your own preference, which I marked as "tunable". So, if I use vi-sensor (the one used by euroc) for urban driving test, the config file could be the same as what I show here for the euroc dataset.
