### ISSUE TITLE
I want to record R-VIO's trajety of EUROC dataset for compare it's traj and ape and rmse . Could you tell me how to record it ?

### ISSUE THREAD

**Issue by sunt40** [rpng/R-VIO#20]

**Comment by huaizheng** [comment]
Yes, this has already been realized which can be turned on from the config file, and the result is in the euroc format.

**Comment by sunt40** [comment]
I have read the rvio_euroc.yaml andrvio_rviz.rviz , but I don't find it . Could please tell me where is it?

**Comment by jcremona** [comment]
Set the parameter INI.RecordOutputs to 1 in rvio_euroc.yaml:
INI.RecordOutputs: 1
You can find the output in a file called stamped_pose_ests.dat.
