### ISSUE TITLE
No visualization is seen in RVIZ

### ISSUE THREAD

**Issue by sunt40** [rpng/R-VIO#25]
i follow your tutorial, type:
` roslaunch rvio euroc.launch`
`rviz rvio_rviz.rviz`
`rosbag play --pause V1_01_easy.bag /cam0/image_raw:=/camera/image_raw /imu0:=/imu`
But No trace is seen in RVIZ.
How to solve it ?

**Comment by moshanATucsd** [comment]
You need to hit space to run the rosbag, otherwise it is paused.

**Comment by sunt40** [comment]
The rosbag is run successfully,but no trajectory in RVIZ.

**Comment by JanOpper** [comment]
Was the Rviz configuration actually loaded? You either have to manually load it in the GUI, or use the command
`rviz -d src/R-VIO/config/rvio_rviz.rviz` to open Rviz and also load the config.
