### ISSUE TITLE
Question about the Ω(w) Matrix.

### ISSUE THREAD

**Issue by Gatsby23** [rpng/R-VIO#26]
Hi, about the Ω(w) matrix in paper 《Robocentric Visual-Inertial Odometry》 
![image](https://user-images.githubusercontent.com/18000675/137878830-f527f3e5-8690-4eba-a516-215a99298424.png)
I'm confused about the right corner number in the equation (18). It should be zero, not one, right?

**Comment by huaizheng** [comment]
Yes, it is a typo when editing. Thanks for pointing it out.
