### ISSUE TITLE
run error ubuntu18.04

### ISSUE THREAD

**Issue by haosen9527** [rpng/R-VIO#31]
double free or corruption (out)
code location : R-VIO/src/rvio/Ransac.cc
 ``` c++ 
 fsSettings["Camera.T_BC0"] >> T;
```
Thank you

**Comment by huaizheng** [comment]
This may be normal for running with a higher version of Ubuntu compared to my test version 16.04, and the version of ROS or the dependencies (e.g., OpenCV) also matters. This seems to be an OpenCV issue about cv::FileStorage.

**Comment by haosen9527** [comment]
> 与我的测试版本 16.04 相比，使用更高版本的 Ubuntu 运行这可能是正常的，并且 ROS 的版本或依赖项（例如 OpenCV 和 Eigen）也很重要。这似乎是关于 cv::FileStorage 的 OpenCV 问题。

thank you !!
