### ISSUE TITLE
Question about the update.

### ISSUE THREAD

**Issue by Gatsby23** [rpng/R-VIO#32]
![Update_Question](https://user-images.githubusercontent.com/18000675/140965100-9e146f62-3c61-4e8b-bd8c-896b6c757787.png)
Sorry to disturbing you. There are some question in the updating process. In Updating process, the error state about the global variable should be 0, right? But why there are still the update correction in line 549？
不好意思，大神。关于更新过程，这里还是有地方不懂想请教您一下。关于状态量中的全局变量，似乎在更新的时候一直为0?但为什么在程序(Updater.cc)第549行依然对它有误差修正呢？

**Comment by huaizheng** [comment]
The global state is jointly estimated along with the other states. Though it is not used to form the measurement model, its covariance with the other states make it possible to be updated every time, therefore, the value of its error state should not be 0.

**Comment by Gatsby23** [comment]
> The global state is jointly estimated along with the other states. Though it is not used to form the measurement model, its covariance with the other states make it possible to be updated every time, therefore, the value of its error state should not be 0.

Thank you for your quickly reply, Thank you very much!
